<?php

namespace Coralion\BolAdvertisingV7\Model;

// This class is auto generated by OpenApi\ModelGenerator
class CreateBiddingModel extends AbstractModel
{
    /**
     * Returns the definition of the model: an associative array with field names as key and
     * field definition as value. The field definition contains of
     * model: Model class or null if it is a scalar type
     * array: Boolean whether it is an array
     * @return array The model definition
     */
    public function getModelDefinition(): array
    {
        return [
            'strategy' => [ 'model' => null, 'array' => false ],
            'automaticBidDesiredAcosPercentage' => [ 'model' => null, 'array' => false ],
            'defaultBid' => [ 'model' => null, 'array' => false ],
        ];
    }

    /**
     * @var string The type of strategy you will use for bidding on advertisements.
     */
    public $strategy;

    /**
     * @var int Only required when the bidding strategy is set to AUTO. When provided, the bidding strategy will attempt
     * to reach this ACoS. The format is a number without decimals that represents a percentage.
     */
    public $automaticBidDesiredAcosPercentage;

    /**
     * @var float The default bid price. The price should always have two decimals precision.
     */
    public $defaultBid;
}
