<?php

namespace Coralion\BolAdvertisingV7\Model;

// This class is auto generated by OpenApi\ModelGenerator
class KeywordPerformance extends AbstractModel
{
    /**
     * Returns the definition of the model: an associative array with field names as key and
     * field definition as value. The field definition contains of
     * model: Model class or null if it is a scalar type
     * array: Boolean whether it is an array
     * @return array The model definition
     */
    public function getModelDefinition(): array
    {
        return [
            'campaignId' => [ 'model' => null, 'array' => false ],
            'adGroupId' => [ 'model' => null, 'array' => false ],
            'keywordId' => [ 'model' => null, 'array' => false ],
            'keywordText' => [ 'model' => null, 'array' => false ],
            'impressions' => [ 'model' => null, 'array' => false ],
            'clicks' => [ 'model' => null, 'array' => false ],
            'ctr' => [ 'model' => null, 'array' => false ],
            'conversions' => [ 'model' => null, 'array' => false ],
            'conversionRate' => [ 'model' => null, 'array' => false ],
            'sales' => [ 'model' => null, 'array' => false ],
            'spent' => [ 'model' => null, 'array' => false ],
            'cpc' => [ 'model' => null, 'array' => false ],
            'acos' => [ 'model' => null, 'array' => false ],
            'roas' => [ 'model' => null, 'array' => false ],
            'averageWinningBid' => [ 'model' => null, 'array' => false ],
        ];
    }

    /**
     * @var string The identifier of the parent-campaign for this ad group.
     */
    public $campaignId;

    /**
     * @var string The identifier of the ad group.
     */
    public $adGroupId;

    /**
     * @var string The identifier of the adgroup.
     */
    public $keywordId;

    /**
     * @var string The text or phrase used in the keyword that caused the ad to be displayed to the user.
     */
    public $keywordText;

    /**
     * @var int The number of impressions from this keyword for ads in the ad group.
     */
    public $impressions;

    /**
     * @var int The number of clicks from this keyword on ads in the ad group.
     */
    public $clicks;

    /**
     * @var float The Click-Through Rate is a ratio of clicks versus impressions from this keyword, with four decimals
     * of precision.
     */
    public $ctr;

    /**
     * @var int The number of product sales that resulted from visitors viewing ads with this keyword, up to 14 days
     * after they viewed the ad.
     */
    public $conversions;

    /**
     * @var float The conversion rate is a ratio of the number of visitors who bought the product up to 14 days after
     * viewing the ad with this keyword, versus those who only viewed the ad, with four decimals of precision.
     */
    public $conversionRate;

    /**
     * @var float The value of sales in EUR that happened up to 14 days after the visitor viewed an ad with this
     * keyword, with two decimals of precision.
     */
    public $sales;

    /**
     * @var float The amount spent on ads with this keyword in EUR, with two decimals of precision.
     */
    public $spent;

    /**
     * @var float The average Cost Per Click of ads with this keyword in EUR, with two decimals of precision.
     */
    public $cpc;

    /**
     * @var float The Advertising Cost Of Sale for the ads with this keyword is a ratio of the ad spend versus sales
     * revenue, with four decimals of precision.
     */
    public $acos;

    /**
     * @var float The Return on Advertising Spent for ads with this keyword is a ratio of sales revenue versus ad spend,
     * with four decimals of precision.
     */
    public $roas;

    /**
     * @var float The value of the average winning bid for ads that used this keyword in the ad group in EUR, with two
     * decimals of precision.
     */
    public $averageWinningBid;
}
