<?php

namespace Coralion\BolAdvertisingV7\Model;

// This class is auto generated by OpenApi\ModelGenerator
class NegativeKeyword extends AbstractModel
{
    /**
     * Returns the definition of the model: an associative array with field names as key and
     * field definition as value. The field definition contains of
     * model: Model class or null if it is a scalar type
     * array: Boolean whether it is an array
     * @return array The model definition
     */
    public function getModelDefinition(): array
    {
        return [
            'keywordId' => [ 'model' => null, 'array' => false ],
            'campaignId' => [ 'model' => null, 'array' => false ],
            'adGroupId' => [ 'model' => null, 'array' => false ],
            'state' => [ 'model' => null, 'array' => false ],
            'keywordText' => [ 'model' => null, 'array' => false ],
            'matchType' => [ 'model' => null, 'array' => false ],
        ];
    }

    /**
     * @var string The identifier of the negative keyword.
     */
    public $keywordId;

    /**
     * @var string The identifier of the parent campaign.
     */
    public $campaignId;

    /**
     * @var string The identifier of the parent ad group.
     */
    public $adGroupId;

    /**
     * @var string The state of the negative keyword.
     */
    public $state;

    /**
     * @var string The text or phrase used in the negative keyword that caused the ad not to be displayed to the user.
     */
    public $keywordText;

    /**
     * @var string The match type that relates the negative keyword and the search term.
     */
    public $matchType;
}
