<?php

namespace Coralion\BolAdvertisingV7\Model;

// This class is auto generated by OpenApi\ModelGenerator
class ProductPerformance extends AbstractModel
{
    /**
     * Returns the definition of the model: an associative array with field names as key and
     * field definition as value. The field definition contains of
     * model: Model class or null if it is a scalar type
     * array: Boolean whether it is an array
     * @return array The model definition
     */
    public function getModelDefinition(): array
    {
        return [
            'campaignId' => [ 'model' => null, 'array' => false ],
            'adGroupId' => [ 'model' => null, 'array' => false ],
            'targetProductId' => [ 'model' => null, 'array' => false ],
            'ean' => [ 'model' => null, 'array' => false ],
            'impressions' => [ 'model' => null, 'array' => false ],
            'clicks' => [ 'model' => null, 'array' => false ],
            'ctr' => [ 'model' => null, 'array' => false ],
            'conversions' => [ 'model' => null, 'array' => false ],
            'conversionRate' => [ 'model' => null, 'array' => false ],
            'sales' => [ 'model' => null, 'array' => false ],
            'conversionsOtherEan' => [ 'model' => null, 'array' => false ],
            'salesOtherEan' => [ 'model' => null, 'array' => false ],
            'spent' => [ 'model' => null, 'array' => false ],
            'cpc' => [ 'model' => null, 'array' => false ],
            'acos' => [ 'model' => null, 'array' => false ],
            'roas' => [ 'model' => null, 'array' => false ],
        ];
    }

    /**
     * @var string The identifier of the parent-campaign for the ad group.
     */
    public $campaignId;

    /**
     * @var string The identifier of the ad group.
     */
    public $adGroupId;

    /**
     * @var string The identifier of the target product.
     */
    public $targetProductId;

    /**
     * @var string The EAN number associated with this product.
     */
    public $ean;

    /**
     * @var int The number of impressions for the ads in the ad group.
     */
    public $impressions;

    /**
     * @var int The number of clicks on ads in the ad group.
     */
    public $clicks;

    /**
     * @var float The Click-Through Rate is a ratio of clicks versus impressions, with four decimals of precision.
     */
    public $ctr;

    /**
     * @var int The number of product sales that resulted from visitors viewing ads in this ad group, up to 14 days
     * after they viewed the ad.
     */
    public $conversions;

    /**
     * @var float The conversion rate is a ratio of the number of visitors who bought the product up to 14 days after
     * viewing the ad, versus those who only viewed the ad, with four decimals of precision.
     */
    public $conversionRate;

    /**
     * @var float The value of sales in EUR that happened up to 14 days after the visitor viewed an ad, with two
     * decimals of precision.
     */
    public $sales;

    /**
     * @var float The number of conversions of similar products with a different EAN up to 14 days after a visitor
     * viewed an ad.
     */
    public $conversionsOtherEan;

    /**
     * @var float The value of sales in EUR of similar products with a different EAN up to 14 days after a visitor
     * viewed an ad, with two decimals of precision.
     */
    public $salesOtherEan;

    /**
     * @var float The amount spent on the product in the ad group in EUR, with two decimals of precision.
     */
    public $spent;

    /**
     * @var float The average Cost Per Click in EUR, with two decimals of precision.
     */
    public $cpc;

    /**
     * @var float The Advertising Cost Of Sale for the ad group is a ratio of the ad spend versus sales revenue, with
     * four decimals of precision.
     */
    public $acos;

    /**
     * @var float The Return on Advertising Spent for the products in the ad group is a ratio of sales revenue versus ad
     * spend, with four decimals of precision.
     */
    public $roas;
}
